CREATE USER 'moviestoreuser'@'%';
ALTER USER 'moviestoreuser'@'%'
IDENTIFIED BY 'user_password' ;
GRANT Event ON *.* TO 'moviestoreuser'@'%';
GRANT File ON *.* TO 'moviestoreuser'@'%';
GRANT Process ON *.* TO 'moviestoreuser'@'%';
GRANT Reload ON *.* TO 'moviestoreuser'@'%';
GRANT Show databases ON *.* TO 'moviestoreuser'@'%';
GRANT Create tablespace ON *.* TO 'moviestoreuser'@'%';
GRANT Usage ON *.* TO 'moviestoreuser'@'%';
GRANT Alter ON moviestoredb.* TO 'moviestoreuser'@'%';
GRANT Create ON moviestoredb.* TO 'moviestoreuser'@'%';
GRANT Create view ON moviestoredb.* TO 'moviestoreuser'@'%';
GRANT Delete ON moviestoredb.* TO 'moviestoreuser'@'%';
GRANT Delete history ON moviestoredb.* TO 'moviestoreuser'@'%';
GRANT Drop ON moviestoredb.* TO 'moviestoreuser'@'%';
GRANT Grant option ON moviestoredb.* TO 'moviestoreuser'@'%';
GRANT Index ON moviestoredb.* TO 'moviestoreuser'@'%';
GRANT Insert ON moviestoredb.* TO 'moviestoreuser'@'%';
GRANT References ON moviestoredb.* TO 'moviestoreuser'@'%';
GRANT Select ON moviestoredb.* TO 'moviestoreuser'@'%';
GRANT Show view ON moviestoredb.* TO 'moviestoreuser'@'%';
GRANT Trigger ON moviestoredb.* TO 'moviestoreuser'@'%';
GRANT Update ON moviestoredb.* TO 'moviestoreuser'@'%';
GRANT Alter routine ON moviestoredb.* TO 'moviestoreuser'@'%';
GRANT Create routine ON moviestoredb.* TO 'moviestoreuser'@'%';
GRANT Create temporary tables ON moviestoredb.* TO 'moviestoreuser'@'%';
GRANT Execute ON moviestoredb.* TO 'moviestoreuser'@'%';
GRANT Lock tables ON moviestoredb.* TO 'moviestoreuser'@'%';
FLUSH PRIVILEGES;
