CREATE TABLE moviestoredb.rental (
	id BIGINT UNSIGNED auto_increment NOT NULL,
	rent DATE NOT NULL,
	back DATE NOT NULL,
	updated TIMESTAMP NOT NULL,
	CONSTRAINT rental_PK PRIMARY KEY (id),
	CONSTRAINT rental_FK FOREIGN KEY (id) REFERENCES moviestoredb.staff(id) ON DELETE RESTRICT ON UPDATE CASCADE,
	CONSTRAINT rental_FK_1 FOREIGN KEY (id) REFERENCES moviestoredb.inventory(id) ON DELETE RESTRICT ON UPDATE CASCADE,
	CONSTRAINT rental_FK_2 FOREIGN KEY (id) REFERENCES moviestoredb.customer(id) ON DELETE RESTRICT ON UPDATE CASCADE
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8
COLLATE=utf8_general_ci
COMMENT='rental data table';
